[redlib]
src.git = "https://github.com/redlib-org/redlib"
fetch.github = "redlib-org/redlib"
cargo_locks = [ "Cargo.lock" ]
# extract = [ "Cargo.lock" ]

[cross-seed]
src.git = "https://github.com/cross-seed/cross-seed"
fetch.github = "cross-seed/cross-seed"

[gamescope]
src.git = "https://github.com/ValveSoftware/gamescope"
fetch.github = "ValveSoftware/gamescope"
git.fetchSubmodules = true
