# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cross-seed = {
    pname = "cross-seed";
    version = "05052f25f991dabba9d6664d61c779a28da9e872";
    src = fetchFromGitHub {
      owner = "cross-seed";
      repo = "cross-seed";
      rev = "05052f25f991dabba9d6664d61c779a28da9e872";
      fetchSubmodules = false;
      sha256 = "sha256-WdKd20vzJfWvnZKBID6IzXOScrZgPKDDafzT2PY9N9k=";
    };
    date = "2025-09-26";
  };
  gamescope = {
    pname = "gamescope";
    version = "0d3a19791de447a673e315a5aed3f59ad64ebb71";
    src = fetchFromGitHub {
      owner = "ValveSoftware";
      repo = "gamescope";
      rev = "0d3a19791de447a673e315a5aed3f59ad64ebb71";
      fetchSubmodules = true;
      sha256 = "sha256-AT66/QMzvTHCe/j/ju2c8hKjjOGGew1gux8sgiVhl/8=";
    };
    date = "2025-10-04";
  };
  redlib = {
    pname = "redlib";
    version = "2dc6b5f3c0db1f8e78a74048ba4550ba6202cb55";
    src = fetchFromGitHub {
      owner = "redlib-org";
      repo = "redlib";
      rev = "2dc6b5f3c0db1f8e78a74048ba4550ba6202cb55";
      fetchSubmodules = false;
      sha256 = "sha256-Di3ZZZ4UqR00ud6MdrnJGUngdd/RSC1uNKlsmTdUx2k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./redlib-2dc6b5f3c0db1f8e78a74048ba4550ba6202cb55/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-10-06";
  };
}
