# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-fish = {
    pname = "catppuccin-fish";
    version = "521560ce2075ca757473816aa31914215332bac9";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "521560ce2075ca757473816aa31914215332bac9";
      fetchSubmodules = false;
      sha256 = "sha256-5CXdzym6Vp+FbKTVBtVdWoh3dODudADIzOLXIyIIxgQ=";
    };
    date = "2026-01-06";
  };
  catppuccin-gitea = {
    pname = "catppuccin-gitea";
    version = "v1.0.2";
    src = fetchTarball {
      url = "https://github.com/catppuccin/gitea/releases/download/v1.0.2/catppuccin-gitea.tar.gz";
      sha256 = "sha256-rZHLORwLUfIFcB6K9yhrzr+UwdPNQVSadsw6rg8Q7gs=";
    };
  };
  cross-seed = {
    pname = "cross-seed";
    version = "d361fec525dba4fa9cc223256a3001003e2f2530";
    src = fetchFromGitHub {
      owner = "cross-seed";
      repo = "cross-seed";
      rev = "d361fec525dba4fa9cc223256a3001003e2f2530";
      fetchSubmodules = false;
      sha256 = "sha256-PTOq006bHhFCKJd8upgliE75BxZOnI3pKkwjX2uQaes=";
    };
    date = "2026-01-17";
  };
  gamescope = {
    pname = "gamescope";
    version = "1164ac17849b0c50a39d286e8feda877d82bb59a";
    src = fetchFromGitHub {
      owner = "ValveSoftware";
      repo = "gamescope";
      rev = "1164ac17849b0c50a39d286e8feda877d82bb59a";
      fetchSubmodules = true;
      sha256 = "sha256-hPuAy5ehT8Njd6HY4qa5/ZASZ7jN+AdCiALpK+RUDyM=";
    };
    date = "2026-01-12";
  };
  mpv-ytsub = {
    pname = "mpv-ytsub";
    version = "14c4e878e52bc6bed2cf636683f7ab43c3d01b1a";
    src = fetchFromGitHub {
      owner = "Idlusen";
      repo = "mpv-ytsub";
      rev = "14c4e878e52bc6bed2cf636683f7ab43c3d01b1a";
      fetchSubmodules = false;
      sha256 = "sha256-WGEXXkwHif+CMEYjWS4tnbd5xO9mIco5Jd8FIHQ+NC4=";
    };
    date = "2025-12-27";
  };
  redlib = {
    pname = "redlib";
    version = "ba98178bbce0f62265095ba085128c7022e51a1f";
    src = fetchFromGitHub {
      owner = "redlib-org";
      repo = "redlib";
      rev = "ba98178bbce0f62265095ba085128c7022e51a1f";
      fetchSubmodules = false;
      sha256 = "sha256-ERTEoT7w8oGA0ztrzc9r9Bl/7OOay+APg3pW+h3tgvM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./redlib-ba98178bbce0f62265095ba085128c7022e51a1f/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-12-15";
  };
}
