# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-fish = {
    pname = "catppuccin-fish";
    version = "6a85af2ff722ad0f9fbc8424ea0a5c454661dfed";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "6a85af2ff722ad0f9fbc8424ea0a5c454661dfed";
      fetchSubmodules = false;
      sha256 = "sha256-Oc0emnIUI4LV7QJLs4B2/FQtCFewRFVp7EDv8GawFsA=";
    };
    date = "2025-03-01";
  };
  catppuccin-gitea = {
    pname = "catppuccin-gitea";
    version = "v1.0.2";
    src = fetchTarball {
      url = "https://github.com/catppuccin/gitea/releases/download/v1.0.2/catppuccin-gitea.tar.gz";
      sha256 = "sha256-rZHLORwLUfIFcB6K9yhrzr+UwdPNQVSadsw6rg8Q7gs=";
    };
  };
  cross-seed = {
    pname = "cross-seed";
    version = "66c5fac7f95cff3838b887301a230ee2a0afd382";
    src = fetchFromGitHub {
      owner = "cross-seed";
      repo = "cross-seed";
      rev = "66c5fac7f95cff3838b887301a230ee2a0afd382";
      fetchSubmodules = false;
      sha256 = "sha256-zE75ljiAIrjBtz2hAagVi2znmIiVkVmpnoR5RBu+W+k=";
    };
    date = "2025-11-10";
  };
  gamescope = {
    pname = "gamescope";
    version = "32606071639437fc15c40f5f2329d84cb78ea6cd";
    src = fetchFromGitHub {
      owner = "ValveSoftware";
      repo = "gamescope";
      rev = "32606071639437fc15c40f5f2329d84cb78ea6cd";
      fetchSubmodules = true;
      sha256 = "sha256-Qc2Fa2UfoUiuwi60xFi/yWaVfS0B/BOSFdO8LbkS7is=";
    };
    date = "2025-11-19";
  };
  redlib = {
    pname = "redlib";
    version = "2dc6b5f3c0db1f8e78a74048ba4550ba6202cb55";
    src = fetchFromGitHub {
      owner = "redlib-org";
      repo = "redlib";
      rev = "2dc6b5f3c0db1f8e78a74048ba4550ba6202cb55";
      fetchSubmodules = false;
      sha256 = "sha256-Di3ZZZ4UqR00ud6MdrnJGUngdd/RSC1uNKlsmTdUx2k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./redlib-2dc6b5f3c0db1f8e78a74048ba4550ba6202cb55/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-10-06";
  };
}
