# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/.btrfsroot" =
    { device = "/dev/disk/by-uuid/112535b6-4318-4d26-812b-7baf0d65dae5";
      fsType = "btrfs";
      options = [ "subvol=/" ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/112535b6-4318-4d26-812b-7baf0d65dae5";
      fsType = "btrfs";
      options = [ "subvol=nixos/@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/112535b6-4318-4d26-812b-7baf0d65dae5";
      fsType = "btrfs";
      options = [ "subvol=nixos/@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/112535b6-4318-4d26-812b-7baf0d65dae5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/18e0dfd8-78bd-478d-9df8-1c28bc0b55df";
      fsType = "ext4";
    };

  fileSystems."/opt/hassio" =
    { device = "/dev/disk/by-uuid/112535b6-4318-4d26-812b-7baf0d65dae5";
      fsType = "btrfs";
      options = [ "subvol=/@hassio" ];
    };

  fileSystems."/opt/hassio/.snapshots" =
    { device = "/dev/disk/by-uuid/112535b6-4318-4d26-812b-7baf0d65dae5";
      fsType = "btrfs";
      options = [ "subvol=/snapshots/@hassio" ];
    };


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}

