# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2d9b0900-88fc-4927-a92a-0047a3589fc7";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/34E0-CC53";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/.mounts/0" = {
    device = "/dev/disk/by-uuid/dbc03bd0-5dee-4c09-b00e-b6f2f8a60791";
    fsType = "ext4";
  };

  fileSystems."/var/lib/private/atticd" = {
    device = "/.mounts/0/atticd";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/.mounts/1" = {
    device = "/dev/disk/by-uuid/d4d0b2a0-a3e3-42bd-a0d6-7188466893d4";
    fsType = "btrfs";
    options = [ "subvol=/" ];
  };

  swapDevices = [];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
