# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cross-seed = {
    pname = "cross-seed";
    version = "05052f25f991dabba9d6664d61c779a28da9e872";
    src = fetchFromGitHub {
      owner = "cross-seed";
      repo = "cross-seed";
      rev = "05052f25f991dabba9d6664d61c779a28da9e872";
      fetchSubmodules = false;
      sha256 = "sha256-WdKd20vzJfWvnZKBID6IzXOScrZgPKDDafzT2PY9N9k=";
    };
    date = "2025-09-26";
  };
  gamescope = {
    pname = "gamescope";
    version = "0d3a19791de447a673e315a5aed3f59ad64ebb71";
    src = fetchFromGitHub {
      owner = "ValveSoftware";
      repo = "gamescope";
      rev = "0d3a19791de447a673e315a5aed3f59ad64ebb71";
      fetchSubmodules = true;
      sha256 = "sha256-AT66/QMzvTHCe/j/ju2c8hKjjOGGew1gux8sgiVhl/8=";
    };
    date = "2025-10-04";
  };
  redlib = {
    pname = "redlib";
    version = "a989d19ca92713878e9a20dead4252f266dc4936";
    src = fetchFromGitHub {
      owner = "redlib-org";
      repo = "redlib";
      rev = "a989d19ca92713878e9a20dead4252f266dc4936";
      fetchSubmodules = false;
      sha256 = "sha256-YJZVkCi8JQ1U47s52iOSyyf32S3b35pEqw4YTW8FHVY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./redlib-a989d19ca92713878e9a20dead4252f266dc4936/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2025-09-09";
  };
}
