# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  redlib = {
    pname = "redlib";
    version = "a989d19ca92713878e9a20dead4252f266dc4936";
    src = fetchFromGitHub {
      owner = "redlib-org";
      repo = "redlib";
      rev = "a989d19ca92713878e9a20dead4252f266dc4936";
      fetchSubmodules = false;
      sha256 = "sha256-YJZVkCi8JQ1U47s52iOSyyf32S3b35pEqw4YTW8FHVY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./redlib-a989d19ca92713878e9a20dead4252f266dc4936/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-09-09";
  };
}
