# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cross-seed = {
    pname = "cross-seed";
    version = "aa2f089fb008b3cd4eb8210445f46b6eda59152c";
    src = fetchFromGitHub {
      owner = "cross-seed";
      repo = "cross-seed";
      rev = "aa2f089fb008b3cd4eb8210445f46b6eda59152c";
      fetchSubmodules = false;
      sha256 = "sha256-fEqO98B9sQEsI81q6fT1zGVXN747MM+nb/M5YkTUGKA=";
    };
    date = "2025-09-15";
  };
  redlib = {
    pname = "redlib";
    version = "a989d19ca92713878e9a20dead4252f266dc4936";
    src = fetchFromGitHub {
      owner = "redlib-org";
      repo = "redlib";
      rev = "a989d19ca92713878e9a20dead4252f266dc4936";
      fetchSubmodules = false;
      sha256 = "sha256-YJZVkCi8JQ1U47s52iOSyyf32S3b35pEqw4YTW8FHVY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./redlib-a989d19ca92713878e9a20dead4252f266dc4936/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-09-09";
  };
}
