name: Build and upload to Attic cache
on:
  push:
    branches:
      - "build-test"

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      # free useless disk space
      - run: 'curl https://raw.githubusercontent.com/apache/arrow/31747f067a6ae29eca2d9bc68748500a8163d83e/ci/scripts/util_free_space.sh | bash'
      - run: 'nix build .#nixosConfigurations.nullbox.config.system.build.toplevel'
